{
    'name': 'School Management',
    'version': '18.0.1.1.0',
    'summary': 'Odoo School Management',
    'description': "The specific and easy-to-use School Managemnt system in Odoo allows you to keep track of your school administration",
    'category': 'Education',
    'author': 'Mehbin Abdulla',
    'depends': ['base','event','sale','l10n_in'],
    'sequence':2,
    'images': [
        'static/description/icon.png'
    ],
    'data': [
        'security/ir.model.access.csv',
        'data/sequence_data.xml',
        'data/school_department_data.xml',
        'data/school_class_data.xml',
        'data/school_subject_data.xml',
        'data/mail_template_data.xml',
        'data/ir_cron_data.xml',
        'data/ir_actions_server_data.xml',
        'views/student_views.xml',
        'views/school_class_views.xml',
        'views/school_department_views.xml',
        'views/school_subject_views.xml',
        'views/school_academic_year_views.xml',
        'views/school_event_views.xml',
        'views/school_club_views.xml',
        'views/sale_order_views.xml',
        'views/partner_views.xml',
        'views/leave_views.xml',
        'views/exam_views.xml',
        'views/student_attendance_views.xml',
        'views/school_management_menu.xml',
    ],
    'web_icon': 'static/description/icon.png',
    'installable': True,
    'application': True,
    'license': 'LGPL-3',
}
